# Generated by Django 5.0 on 2024-02-23 14:51

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_description_alter_task_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_video_hash',
            field=models.CharField(blank=True, help_text="from Youtube's video URL copy the part after 'https://www.youtube.com/watch?v='.", max_length=50, null=True, verbose_name='YouTube video hash'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.IntegerField(choices=[(0, '&#x2764;&#xfe0f;'), (1, '&#128163;'), (2, '&#128293;'), (3, '&#128077;'), (4, '&#128405;'), (5, '&#128078;')], default=3, verbose_name='type')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tasks.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'project like',
                'verbose_name_plural': 'project likes',
            },
        ),
    ]
